reactions_and_info = {'HEX1': {
    'stoichiometry': {'atp_c': -1.0, 'glc__D_c': -1.0, 'adp_c': 1.0,
                      'g6p_c': 1.0, 'h_c': 1.0}, 'upper_bound': 1000.0,
    'lower_bound': 0.0, 'name': 'Hexokinase (D-glucose:ATP)',
    'gene_reaction_rule': 'b2388'},
                      'PGI': {'stoichiometry': {'g6p_c': -1.0, 'f6p_c': 1.0},
                              'upper_bound': 1000.0, 'lower_bound': -1000.0,
                              'name': 'Glucose-6-phosphate isomerase',
                              'gene_reaction_rule': 'b4025'}, 'PFK': {
        'stoichiometry': {'atp_c': -1.0, 'f6p_c': -1.0, 'adp_c': 1.0,
                          'fdp_c': 1.0, 'h_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0, 'name': 'Phosphofructokinase',
        'gene_reaction_rule': 'b3916 or b1723'},
                      'TPI': {'stoichiometry': {'dhap_c': -1.0, 'g3p_c': 1.0},
                              'upper_bound': 1000.0, 'lower_bound': -1000.0,
                              'name': 'Triose-phosphate isomerase',
                              'gene_reaction_rule': 'b3919'}, 'FBA': {
        'stoichiometry': {'fdp_c': -1.0, 'g3p_c': 1.0},
        'upper_bound': 1000.0, 'lower_bound': -1000.0,
        'name': 'Fructose-bisphosphate aldolase',
        'gene_reaction_rule': 'b1773 or b2097 or b2925'}, 'GAPD': {
        'stoichiometry': {'g3p_c': -1.0, 'nad_c': -1.0, 'pi_c': -1.0,
                          '13dpg_c': 1.0, 'h_c': 1.0, 'nadh_c': 1.0},
        'upper_bound': 1000.0, 'lower_bound': -1000.0,
        'name': 'Glyceraldehyde-3-phosphate dehydrogenase',
        'gene_reaction_rule': 'b1779'}, 'PGK': {
        'stoichiometry': {'3pg_c': -1.0, 'atp_c': -1.0, '13dpg_c': 1.0,
                          'adp_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': -1000.0, 'name': 'Phosphoglycerate kinase',
        'gene_reaction_rule': 'b2926'},
                      'PGM': {'stoichiometry': {'2pg_c': -1.0, '3pg_c': 1.0},
                              'upper_bound': 1000.0, 'lower_bound': -1000.0,
                              'name': 'Phosphoglycerate mutase',
                              'gene_reaction_rule': 'b4395 or b3612 or b0755'},
                      'ENO': {'stoichiometry': {'2pg_c': -1.0, 'h2o_c': 1.0,
                                                'pep_c': 1.0},
                              'upper_bound': 1000.0, 'lower_bound': -1000.0,
                              'name': 'Enolase',
                              'gene_reaction_rule': 'b2779'}, 'PYK': {
        'stoichiometry': {'adp_c': -1.0, 'h_c': -1.0, 'pep_c': -1.0,
                          'atp_c': 1.0, 'pyr_c': 1.0}, 'upper_bound': 1000.0,
        'lower_bound': 0.0, 'name': 'Pyruvate kinase',
        'gene_reaction_rule': 'b1854 or b1676'}}

metabolites_and_info = {
    'atp_c': {'name': 'ATP C10H12N5O13P3', 'formula': 'C10H12N5O13P3',
              'charge': -4, 'compartment': 'c'},
    'glc__D_c': {'name': 'D-Glucose', 'formula': 'C6H12O6', 'charge': 0,
                 'compartment': 'c'},
    'adp_c': {'name': 'ADP C10H12N5O10P2', 'formula': 'C10H12N5O10P2',
              'charge': -3, 'compartment': 'c'},
    'g6p_c': {'name': 'D-Glucose 6-phosphate', 'formula': 'C6H11O9P',
              'charge': -2, 'compartment': 'c'},
    'h_c': {'name': 'H+', 'formula': 'H', 'charge': 1, 'compartment': 'c'},
    'f6p_c': {'name': 'D-Fructose 6-phosphate', 'formula': 'C6H11O9P',
              'charge': -2, 'compartment': 'c'},
    'fdp_c': {'name': 'D-Fructose 1,6-bisphosphate', 'formula': 'C6H10O12P2',
              'charge': -4, 'compartment': 'c'},
    'dhap_c': {'name': 'Dihydroxyacetone phosphate', 'formula': 'C3H5O6P',
               'charge': -2, 'compartment': 'c'},
    'g3p_c': {'name': 'Glyceraldehyde 3-phosphate', 'formula': 'C3H5O6P',
              'charge': -2, 'compartment': 'c'},
    'nad_c': {'name': 'Nicotinamide adenine dinucleotide',
              'formula': 'C21H26N7O14P2', 'charge': -1, 'compartment': 'c'},
    'pi_c': {'name': 'Phosphate', 'formula': 'HO4P', 'charge': -2,
             'compartment': 'c'},
    '13dpg_c': {'name': '3-Phospho-D-glyceroyl phosphate',
                'formula': 'C3H4O10P2', 'charge': -4, 'compartment': 'c'},
    'nadh_c': {'name': 'Nicotinamide adenine dinucleotide - reduced',
               'formula': 'C21H27N7O14P2', 'charge': -2, 'compartment': 'c'},
    '3pg_c': {'name': '3-Phospho-D-glycerate', 'formula': 'C3H4O7P',
              'charge': -3, 'compartment': 'c'},
    '2pg_c': {'name': 'D-Glycerate 2-phosphate', 'formula': 'C3H4O7P',
              'charge': -3, 'compartment': 'c'},
    'h2o_c': {'name': 'H2O H2O', 'formula': 'H2O', 'charge': 0,
              'compartment': 'c'},
    'pep_c': {'name': 'Phosphoenolpyruvate', 'formula': 'C3H2O6P',
              'charge': -3, 'compartment': 'c'},
    'pyr_c': {'name': 'Pyruvate', 'formula': 'C3H3O3', 'charge': -1,
              'compartment': 'c'}}
